bzero(Jlist[LINK1], sizeof(Jlist[LINK1]));
Jlist[LINK1][JA] = 1;
bzero(Jlist[LINK2], sizeof(Jlist[LINK2]));
Jlist[LINK2][JB] = 1;
Jlist[LINK2][JA] = 1;
bzero(Jlist[LINK3], sizeof(Jlist[LINK3]));
Jlist[LINK3][JC] = 1;
Jlist[LINK3][JB] = 1;
Jlist[LINK3][JA] = 1;
bzero(Jlist[LINK4], sizeof(Jlist[LINK4]));
Jlist[LINK4][JD] = 1;
Jlist[LINK4][JC] = 1;
Jlist[LINK4][JB] = 1;
Jlist[LINK4][JA] = 1;
bzero(Jlist[LINK5], sizeof(Jlist[LINK5]));
Jlist[LINK5][JE] = 1;
Jlist[LINK5][JD] = 1;
Jlist[LINK5][JC] = 1;
Jlist[LINK5][JB] = 1;
Jlist[LINK5][JA] = 1;
