function acrobotmodel = Acrobot()
% A structure describing the robot kinematics and the inertia
%  parameters according to the model described in "A beginner's guide
%  to 6-D vectors (part 2)" by Roy Featherstone.
%
%  This file has been automatically generated by the robotics code
%  generator developed by Marco Frigerio at the Italian Institute of
%  Technology.


acrobotmodel.robotname = 'Acrobot';

acrobotmodel.NB = 2;
acrobotmodel.parent = zeros(1, 2);

acrobotmodel.parent(1) = 0;
acrobotmodel.parent(2) = 1;

acrobotmodel.jtype{1} =  'Rz' ;
acrobotmodel.jtype{2} =  'Rz' ;

acrobotmodel.Xtree{1} = rotz(0.0 ) * ...
roty(0.0 ) * ...
rotx(0.0 ) * ...
xlt([0.0 0.0 0.0]);
;
acrobotmodel.Xtree{2} = rotz(0.0 ) * ...
roty(0.0 ) * ...
rotx(0.0 ) * ...
xlt([1.0 0.0 0.0]);
;


tmpI   = [[  0.0025,	-(0.0),	-(0.0)];
 [-(0.0),	  0.33458 ,	-(0.0)];
 [-(0.0),	-(0.0),	  0.33458]];
tmpC   = skew([0.5; 0.0; 0.0]);
tmpMass= 1.0;
acrobotmodel.I{1} = [tmpI, tmpMass*tmpC; tmpMass*tmpC', eye(3)*tmpMass];


tmpI   = [[  0.0025,	-(0.0),	-(0.0)];
 [-(0.0),	  0.33458 ,	-(0.0)];
 [-(0.0),	-(0.0),	  0.33458]];
tmpC   = skew([0.5; 0.0; 0.0]);
tmpMass= 1.0;
acrobotmodel.I{2} = [tmpI, tmpMass*tmpC; tmpMass*tmpC', eye(3)*tmpMass];

