function fancymodel = Fancy(params)
% A structure describing the robot kinematics and the inertia
%  parameters according to the model described in "A beginner's guide
%  to 6-D vectors (part 2)" by Roy Featherstone.
%
%  This file has been automatically generated by the robotics code
%  generator developed by Marco Frigerio at the Italian Institute of
%  Technology.

massParams = params.massParams;

fancymodel.robotname = 'Fancy';

fancymodel.NB = 5;
fancymodel.parent = zeros(1, 5);

fancymodel.parent(1) = 0;
fancymodel.parent(2) = 1;
fancymodel.parent(3) = 2;
fancymodel.parent(4) = 3;
fancymodel.parent(5) = 4;

fancymodel.jtype{1} =  'Rz' ;
fancymodel.jtype{2} =  'Pz' ;
fancymodel.jtype{3} =  'Rz' ;
fancymodel.jtype{4} =  'Pz' ;
fancymodel.jtype{5} =  'Rz' ;

fancymodel.Xtree{1} = rotz(0.0 ) * ...
roty(0.0 ) * ...
rotx(0.0 ) * ...
xlt([0.0 0.0 0.0]);
;
fancymodel.Xtree{2} = rotz(0.0 ) * ...
roty(0.0 ) * ...
rotx(-1.5707964 ) * ...
xlt([(params.lengths.ee_x) 0.0 0.0]);
;
fancymodel.Xtree{3} = rotz(0.0 ) * ...
roty(0.0 ) * ...
rotx(0.0 ) * ...
xlt([0.0 0.0 1.0]);
;
fancymodel.Xtree{4} = rotz(0.0 ) * ...
roty(0.0 ) * ...
rotx(1.5707964 ) * ...
xlt([1.0 0.0 0.0]);
;
fancymodel.Xtree{5} = rotz(0.0 ) * ...
roty(0.0 ) * ...
rotx(0.0 ) * ...
xlt([0.0 0.0 1.0]);
;


tmpI   = [[  0.0025,	-(0.0),	-(0.0)];
 [-(0.0),	  0.33458 ,	-(0.0)];
 [-(0.0),	-(0.0),	  0.33458]];
tmpC   = skew([0.5; 0.0; 0.0]);
tmpMass= 1.0;
fancymodel.I{1} = [tmpI, tmpMass*tmpC; tmpMass*tmpC', eye(3)*tmpMass];


tmpI   = [[  0.33458,	-(0.0),	-(0.0)];
 [-(0.0),	  0.33458 ,	-(0.0)];
 [-(0.0),	-(0.0),	  0.0025]];
tmpC   = skew([0.0; 0.0; 0.5]);
tmpMass= 1.0;
fancymodel.I{2} = [tmpI, tmpMass*tmpC; tmpMass*tmpC', eye(3)*tmpMass];


tmpI   = [[  0.0025,	-(0.0),	-(0.0)];
 [-(0.0),	  0.33458 ,	-(0.0)];
 [-(0.0),	-(0.0),	  0.33458]];
tmpC   = skew([0.5; 0.0; 0.0]);
tmpMass= 1.0;
fancymodel.I{3} = [tmpI, tmpMass*tmpC; tmpMass*tmpC', eye(3)*tmpMass];


tmpI   = [[  0.33458,	-(0.0),	-(0.0)];
 [-(0.0),	  0.33458 ,	-(0.0)];
 [-(0.0),	-(0.0),	  0.0025]];
tmpC   = skew([0.0; 0.0; 0.5]);
tmpMass= 1.0;
fancymodel.I{4} = [tmpI, tmpMass*tmpC; tmpMass*tmpC', eye(3)*tmpMass];


tmpI   = [[  0.0025,	-(0.0),	-(0.0)];
 [-(0.0),	  0.33458 ,	-(0.0)];
 [-(0.0),	-(0.0),	  0.33458]];
tmpC   = skew([0.5; 0.0; 0.0]);
tmpMass= 1.0;
fancymodel.I{5} = [tmpI, tmpMass*tmpC; tmpMass*tmpC', eye(3)*tmpMass];

